name: Build C++ EXE

"on":
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build EXE
        run: g++ sava.cpp -o sava.exe -static -static-libgcc -static-libstdc++

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: sava-exe
          path: sava.exe
