name: Build C++ EXE

on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Ambil kode
        uses: actions/checkout@v4

      - name: Compile C++ menjadi EXE
        run: g++ p
        sava.cpp -o sava.exe

      - name: Simpan file EXE
        uses: actions/upload-artifact@v4
        with:
          name: program-exe
          path: sava.exe
